version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      ES_JAVA_OPTS: "-Xms1000m -Xmx1000m"
      discovery.type: single-node
      xpack.security.enabled: false
      http.port: ${ES_PORT}
    ports:
      - ${ES_PORT}:${ES_PORT}
    volumes:
      - es_data_tests:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://${ES_HOST}:${ES_PORT}/_cluster/health?wait_for_status=yellow&timeout=5s" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7.2.4
    volumes:
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - ${REDIS_PORT}
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  tests:
    build:
      context: ./fastapi-project
      target: tests
    env_file:
      - .env
    depends_on:
      api:
        condition: service_started

  api:
    build:
      context: ./fastapi-project
      target: dev
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      ES_HOST: ${ES_HOST}
      ES_PORT: ${ES_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      PROJECT_NAME: ${PROJECT_NAME}
      API_PORT: ${API_PORT}
    volumes:
      - ./fastapi-project/src:/app/src
      - ./fastapi-project/main.py:/app/main.py
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  es_data_tests: