services:
  redis:
    ports:
      - '6379:6379'
  elasticsearch:
    ports:
      - '9200:9200'
  api:
    build:
      context: ./fastapi-project
      target: dev
    ports:
      - '8000:8000'
    volumes:
      - ./fastapi-project/src:/app/src
      - ./fastapi-project/main.py:/app/main.py
