services:
  elasticsearch:
    ports:
      - '9200:9200'
  api:
    build:
      context: ./fastapi-project
      target: dev
    volumes:
      - ./fastapi-project/src:/app/src
      - ./fastapi-project/main.py:/app/main.py
