services:
  redis:
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  elasticsearch:
    ports:
      - ${ES_PORT}:${ES_PORT}

  api:
    build:
      context: ./fastapi-project
      target: dev
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./fastapi-project/src:/app/src
      - ./fastapi-project/main.py:/app/main.py
