services:
  api:
    build:
      context: ./fastapi-project
      target: dev
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./fastapi-project/src:/app/src
      - ./fastapi-project/main.py:/app/main.py

  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      ES_JAVA_OPTS: "-Xms1000m -Xmx1000m"
      discovery.type: single-node
      xpack.security.enabled: false
      http.port: ${ES_PORT}
    ports:
      - ${ES_PORT}:${ES_PORT}
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://${ES_HOST}:${ES_PORT}/_cluster/health?wait_for_status=yellow&timeout=5s" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  es_data:
